spring.application.name=joboffers

http.client.config.uri=http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com:5057
http.client.config.port=5057
http.client.config.connectTimeout=10000
http.client.config.readTimeout=5000

offers.fetching.cron=0 0 */3 * * *